# permissions for end users to edit uncores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: uncore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-power-manager
    app.kubernetes.io/part-of: kubernetes-power-manager
    app.kubernetes.io/managed-by: kustomize
  name: uncore-editor-role
rules:
  - apiGroups:
      - power.intel.com
    resources:
      - uncores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - power.intel.com
    resources:
      - uncores/status
    verbs:
      - get
