---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: powerconfigs.power.intel.com
spec:
  group: power.intel.com
  names:
    kind: PowerConfig
    listKind: PowerConfigList
    plural: powerconfigs
    singular: powerconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: PowerConfig is the Schema for the powerconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PowerConfigSpec defines the desired state of PowerConfig
            properties:
              customDevices:
                description: The CustomDevices include alternative devices that represent
                  other resources
                items:
                  type: string
                type: array
              powerNodeSelector:
                additionalProperties:
                  type: string
                description: The label on the Nodes you the Operator will look for
                  to deploy the Node Agent
                type: object
              powerProfiles:
                description: The PowerProfiles that will be created by the Operator
                items:
                  type: string
                type: array
            type: object
          status:
            description: PowerConfigStatus defines the observed state of PowerConfig
            properties:
              errors:
                items:
                  type: string
                type: array
              nodes:
                description: The Nodes that the Node Agent has been deployed to
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
